"""Add extracted_images column

Revision ID: ad634e73a773
Revises: 
Create Date: 2025-07-24 23:39:58.872516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad634e73a773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_data', schema=None) as batch_op:
        batch_op.drop_column('extracted_images')

    # ### end Alembic commands ###
