"""add_extracted_xml_column

Revision ID: f53ca1de3b98
Revises: ad634e73a773
Create Date: 2025-07-30 01:10:25.054687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53ca1de3b98'
down_revision = 'ad634e73a773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_xml', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_data', schema=None) as batch_op:
        batch_op.drop_column('extracted_xml')

    # ### end Alembic commands ###
